### ISSUE TITLE
No spaces are allowed to enter on the module's localization tab in UI

### ISSUE THREAD

**Issue by souryogurt** [vxcontrol/soldr#32]
The soldr's UI doesn't allow to enter spaces in titles and descriptions of events, actions, and variables on the localization tab.

## Steps to reproduce
1. Open soldr's web UI
2. Create a new basic module 
3. Go to the `Localization` tab
4. Enter "This is text with spaces" in any `title` or `description` field.  

## Expected result
The text with spaces is entered and displayed in the UI.
```This is text with spaces```

## Actual Result
The "space" keystrokes are filtered, and text is displayed without spaces as
```Thisistextwithspaces```

## Environment
Browser: Google Chrome Version 107.0.5304.121 (Official Build) (64-bit) for Linux

**Comment by asdek** [comment]
@1mrekq please, check it and prepare the fix
