### ISSUE TITLE
[Bug]: An unaligned 64-bit atomic operation causes the agent to crash

### ISSUE THREAD

**Issue by souryogurt** [vxcontrol/soldr#73]
### Describe the bug

I am trying to launch a 32-bit version of the agent on my machine. I expected it to work typically, but it crashes right after connecting to the server.

### Steps to Reproduce

1. Go to the `Agent distributions` page  in the server's UI and download the `Windows x86` agent; 
2. Launch the downloaded agent:

    ```console
    vxagent_windows_386.exe -connect wss://172.17.0.1:8443
    ```

### Screenshots, screen recording, code snippet

![photo_2023-01-20_20-03-51](https://user-images.githubusercontent.com/1236218/213702013-647d4fe7-818e-4505-9903-5323f33affca.jpg)

### Environment information

- Agent version:  v1.2.0.153-d182a6c

### Which agent binary used?

- [ ] darwin-amd64
- [ ] linux-386
- [ ] linux-amd64
- [X] windows-386
- [ ] windows-amd64

**Comment by souryogurt** [comment]
I looked into this issue a bit, and it seems it is related to [known GO's sync/atomic package bugs](https://pkg.go.dev/sync/atomic#pkg-note-BUG).

I guess we should replace int64 types [in ProtoStats](https://github.com/vxcontrol/soldr/blob/d182a6c9de1407042ac9a06fd39a069ff36dac25/pkg/vxproto/stats.go#L20-L25) with [atomic.Int64](https://pkg.go.dev/sync/atomic#Int64) types because they guarantee alignment.

**Comment by asdek** [comment]
That is done:
https://github.com/vxcontrol/soldr/commit/7d9ee30b75e828eb8d6f0c72b5ea5692e67392f5
